# Generated by Django 2.1.1 on 2019-03-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_subtitle',
            new_name='site_subtagline',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_title',
            new_name='site_tagline',
        ),
    ]
