# Generated by Django 2.1.1 on 2019-03-24 01:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1',
            field=models.ForeignKey(blank=True, help_text='First featured section for the homepage. Will display up to three child items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured section 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_image',
            field=models.ForeignKey(blank=True, help_text='Promo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write some promotional copy', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_title',
            field=models.CharField(blank=True, help_text='Title of the site.', max_length=255, null=True),
        ),
    ]
