# Generated by Django 2.1.1 on 2019-03-24 20:35

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190323_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='site_blurb',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text for the summary of the site.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_blurb_title',
            field=models.CharField(blank=True, help_text='Title to display above the summary of the website.', max_length=255, null=True),
        ),
    ]
