# Generated by Django 2.0.9 on 2019-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='footer_link',
            field=models.CharField(blank=True, help_text='Link to outward sites.', max_length=255, null=True),
        ),
    ]
