# Generated by Django 2.0.9 on 2019-03-25 17:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_links',
            field=wagtail.core.fields.StreamField([('HeaderLink', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('link', wagtail.core.blocks.CharBlock(classname='full title'))]))]),
        ),
        migrations.AlterField(
            model_name='header',
            name='site_title',
            field=wagtail.core.fields.StreamField([('Site_Title', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('link', wagtail.core.blocks.CharBlock(classname='full title'))]))], null=True),
        ),
    ]
