# Generated by Django 2.0.9 on 2019-03-25 22:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190325_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_links',
            field=wagtail.core.fields.StreamField([('Header_Link', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('link', wagtail.core.blocks.CharBlock(classname='full title'))]))]),
        ),
    ]
