# Generated by Django 2.1.8 on 2019-04-01 19:43

import cms_design_electronics.streams.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcdcPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('design_description', wagtail.core.fields.StreamField([('description', cms_design_electronics.streams.blocks.RichtextBlock())], null=True)),
                ('dcdc_type', models.CharField(choices=[('ccm', 'Continuous Conduction Mode'), ('dcm', 'Discontinuous Conduction Mode')], max_length=75, null=True)),
                ('design_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('design_params', modelcluster.fields.ParentalManyToManyField(related_name='_dcdcpage_design_params_+', to='snippets.DCDCDesignParam')),
                ('open_loop_equations', modelcluster.fields.ParentalManyToManyField(related_name='_dcdcpage_open_loop_equations_+', to='snippets.DCDCOpenLoopEquations')),
                ('recommended_components', modelcluster.fields.ParentalManyToManyField(related_name='_dcdcpage_recommended_components_+', to='snippets.DCDCRecComps')),
                ('selected_components', modelcluster.fields.ParentalManyToManyField(related_name='_dcdcpage_selected_components_+', to='snippets.DCDCSelComps')),
            ],
            options={
                'verbose_name': 'DC/DC Converter Page',
                'verbose_name_plural': 'DC/DC Converter Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
