# Generated by Django 2.0.9 on 2019-03-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcdc_converters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdctype',
            name='sidebar_title',
            field=models.TextField(default='Continuous Conduction Mode', help_text='Enter the title of the converter for the sidebar.'),
        ),
    ]
