# Generated by Django 2.0.9 on 2019-03-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcdc_converters', '0002_dcdctype_sidebar_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdc',
            name='name',
            field=models.TextField(blank=True, help_text='Name of the DC/DC converter. Just "Buck Converter" or "Boost" etc. This will be used in the sidebar.'),
        ),
    ]
