# Generated by Django 2.1.8 on 2019-04-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCenterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Design Center Page',
                'verbose_name_plural': 'Design Center Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
