# Generated by Django 2.0.9 on 2019-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCenterSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(help_text='Input to Output Transfer etc.', max_length=100)),
                ('equation', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'DC/DC Converter Open Loop Design Equations',
            },
        ),
    ]
