# Generated by Django 2.0.9 on 2019-03-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('design_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCenter',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('test', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'DC/DC Converter Selected Components for Analysis',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='DesignCenterSnippet',
        ),
    ]
