# Generated by Django 2.1.8 on 2019-04-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCDCDesignEquations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='E.g. Duty Ratio etc.', max_length=150, null=True)),
                ('converter', models.CharField(help_text='E.g. CCM Buck Converter etc.', max_length=100, null=True)),
                ('equation', models.TextField(help_text='Design Equation', null=True)),
            ],
            options={
                'verbose_name_plural': 'DC/DC Converter Design Equations for Analysis',
                'verbose_name': 'DC/DC Converter Design Equation for Analysis',
            },
        ),
        migrations.CreateModel(
            name='DCDCDesignParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'DC/DC Converter Design Parameters',
                'verbose_name': 'DC/DC Converter Design Parameter',
            },
        ),
        migrations.CreateModel(
            name='DCDCOpenLoopEquations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='E.g. Input to Output Transfer etc.', max_length=100, null=True)),
                ('converter', models.CharField(help_text='E.g. CCM Buck Converter etc.', max_length=100, null=True)),
                ('equation', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'DC/DC Converter Open Loop Design Equations',
                'verbose_name': 'DC/DC Converter Open Loop Design Equation',
            },
        ),
        migrations.CreateModel(
            name='DCDCRecComps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(help_text='E.g. C1 vs. L1 vs. etc.', max_length=100, null=True)),
                ('converter', models.CharField(help_text='E.g. CCM Buck Converter vs. etc.', max_length=150, null=True)),
                ('equation', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'DC/DC Converter Recommended Components',
                'verbose_name': 'DC/DC Converter Recommended Component',
            },
        ),
        migrations.CreateModel(
            name='DCDCSelComps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(help_text='E.g. C1 vs. L1 vs. etc.', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'DC/DC Converter Selected Components for Analysis',
                'verbose_name': 'DC/DC Converter Selected Component for Analysis',
            },
        ),
    ]
