# Generated by Django 2.1.1 on 2019-04-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20190403_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcdcdesignequations',
            options={'verbose_name': 'DC/DC Converter: Analysis Result', 'verbose_name_plural': 'DC/DC Converter: Analysis Results'},
        ),
        migrations.AlterModelOptions(
            name='dcdcdesignparam',
            options={'verbose_name': 'DC/DC Converter: Design Parameter', 'verbose_name_plural': 'DC/DC Converter: Design Parameters'},
        ),
        migrations.AlterModelOptions(
            name='dcdcopenloopequations',
            options={'verbose_name': 'DC/DC Converter: Open Loop Transfer Function', 'verbose_name_plural': 'DC/DC Converter: Open Loop Transfer Functions'},
        ),
        migrations.AlterModelOptions(
            name='dcdcreccomps',
            options={'verbose_name': 'DC/DC Converter: Recommended Component', 'verbose_name_plural': 'DC/DC Converter: Recommended Components'},
        ),
        migrations.AlterModelOptions(
            name='dcdcselcomps',
            options={'verbose_name': 'DC/DC Converter: Selected Component', 'verbose_name_plural': 'DC/DC Converter: Selected Components'},
        ),
    ]
