# Generated by Django 2.1.1 on 2019-03-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(blank=True, help_text='Github URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn URL', null=True),
        ),
    ]
